"""Alter LineItem.unit_price to NUMERIC(12,2)

Revision ID: 935b86d56595
Revises: 0c2a35148c65
Create Date: 2025-08-10 10:27:23.285689

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '935b86d56595'
down_revision = '0c2a35148c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
